export enum Permission {
  PLATFORM_MANAGE = 'platform:manage',
  ORG_MANAGE = 'org:manage',
  USERS_MANAGE = 'users:manage',
  JOBS_READ = 'jobs:read',
  JOBS_WRITE = 'jobs:write',
  CANDIDATES_READ = 'candidates:read',
  CANDIDATES_WRITE = 'candidates:write',
  MATCHES_READ = 'matches:read',
  MATCHES_WRITE = 'matches:write',
  COMMUNICATIONS_READ = 'communications:read',
  COMMUNICATIONS_APPROVE = 'communications:approve',
  INTERVIEWS_READ = 'interviews:read',
  INTERVIEWS_WRITE = 'interviews:write',
  FEEDBACK_WRITE = 'feedback:write',
  ANALYTICS_READ = 'analytics:read',
  PORTAL_READ = 'portal:read',
}
